/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: (typeof import('ant-design-vue/es'))['Button']
    ACheckbox: (typeof import('ant-design-vue/es'))['Checkbox']
    ACol: (typeof import('ant-design-vue/es'))['Col']
    AConfigProvider: (typeof import('ant-design-vue/es'))['ConfigProvider']
    ADrawer: (typeof import('ant-design-vue/es'))['Drawer']
    AForm: (typeof import('ant-design-vue/es'))['Form']
    AFormItem: (typeof import('ant-design-vue/es'))['FormItem']
    AInput: (typeof import('ant-design-vue/es'))['Input']
    AInputPassword: (typeof import('ant-design-vue/es'))['InputPassword']
    ALayout: (typeof import('ant-design-vue/es'))['Layout']
    ALayoutContent: (typeof import('ant-design-vue/es'))['LayoutContent']
    ALayoutFooter: (typeof import('ant-design-vue/es'))['LayoutFooter']
    ALayoutHeader: (typeof import('ant-design-vue/es'))['LayoutHeader']
    ALayoutSider: (typeof import('ant-design-vue/es'))['LayoutSider']
    AMenu: (typeof import('ant-design-vue/es'))['Menu']
    AMenuItem: (typeof import('ant-design-vue/es'))['MenuItem']
    ARow: (typeof import('ant-design-vue/es'))['Row']
    ASubMenu: (typeof import('ant-design-vue/es'))['SubMenu']
    IBackground: (typeof import('./src/components/IBackground/IBackground.vue'))['default']
    Icon: (typeof import('./src/components/Icon/Icon.vue'))['default']
    IMenu: (typeof import('./src/components/IMenu/IMenu.vue'))['default']
    ISide: (typeof import('./src/components/ISide/ISide.vue'))['default']
    Layout: (typeof import('./src/components/Layout/Layout.vue'))['default']
    RouterLink: (typeof import('vue-router'))['RouterLink']
    RouterView: (typeof import('vue-router'))['RouterView']
  }
}
